export const SELECT_LIST = 'select_list'
export const UPDATE_EDITING_TODO = 'update_editing_todo'
export const UPDATE_SELECTED_TAGS = 'update_selected_tags'
export const CLEAR_TAGS_FILTER = 'clear_tags_filter'
export const CLEAR_LIST_FILTER = 'clear_list_filter'
